<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SIPL92" failures="0" tests="2" name="connect_OrderProcessSPL.RTE" time="4.179" errors="1" timestamp="2023-07-06T17:42:33 IST" skipped="1">
  <testcase classname="connect_OrderProcessSPL.RTE" name="beforeMethod" time="4.179">
    <error message=".\src\main\resources\NA OCP Result_STG.xlsx (The process cannot access the file because it is being used by another process)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: .\src\main\resources\NA OCP Result_STG.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:236)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:185)
at netAgent_BasePackage.BaseInit.resetResultofExcel(BaseInit.java:1179)
at netAgent_BasePackage.BaseInit.beforeMethod(BaseInit.java:163)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <system-out/>
  <testcase classname="connect_OrderProcessSPL.RTE" name="rteorderprocess" time="0.000">
    <skipped/>
  </testcase> <!-- rteorderprocess -->
  <system-out/>
</testsuite> <!-- connect_OrderProcessSPL.RTE -->
